trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npx cypress install
    displayName: 'Install dependencies and Cypress'

  - script: |
      npx cypress run
    displayName: 'Run Cypress Tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/cypress/results/*.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
